import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "@radix-ui/themes/styles.css";
import QueryClientProvider from "./QueryClientProvider";
import { Container, Theme, ThemePanel } from "@radix-ui/themes";
import "./globals.css";
import { Navbar } from "./NaxBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ height: "100vh", width: "100vw" }}
      >
        <QueryClientProvider>
          <Theme accentColor="violet">
            <Container maxWidth="95vw" maxHeight={"95vh"} align={"center"}>
              <Navbar />

              {children}
            </Container>
          </Theme>
        </QueryClientProvider>
      </body>
    </html>
  );
}
